[2025-08-14T21:46:17.072+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T21:46:15+00:00 [queued]>
[2025-08-14T21:46:17.080+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T21:46:15+00:00 [queued]>
[2025-08-14T21:46:17.081+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-14T21:46:17.090+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 21:46:15+00:00
[2025-08-14T21:46:17.094+0000] {standard_task_runner.py:60} INFO - Started process 31574 to run task
[2025-08-14T21:46:17.098+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'manual__2025-08-14T21:46:15+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpvdd4qcff']
[2025-08-14T21:46:17.101+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask fetch_historical_data
[2025-08-14T21:46:17.157+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T21:46:15+00:00 [running]> on host 0181ae2045ff
[2025-08-14T21:46:17.209+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T21:46:15+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T21:46:15+00:00'
[2025-08-14T21:46:17.211+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T21:46:17.212+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14\n    ']
[2025-08-14T21:46:17.220+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T21:46:17.650+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T21:46:17.651+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T21:46:17.651+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T21:46:17.651+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T21:46:17.695+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T21:46:17.704+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T21:46:17.706+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T214615, start_date=20250814T214617, end_date=20250814T214617
[2025-08-14T21:46:17.714+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 31574)
[2025-08-14T21:46:17.738+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T21:46:17.762+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
