[2025-08-15T00:00:03.954+0000] {processor.py:161} INFO - Started process (PID=39889) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:03.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:03.961+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:03.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:03.982+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:03.976+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:03.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:04.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.130 seconds
[2025-08-15T00:00:14.710+0000] {processor.py:161} INFO - Started process (PID=39899) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:14.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:14.716+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:14.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:14.732+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:14.727+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:14.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:14.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.109 seconds
[2025-08-15T00:00:25.909+0000] {processor.py:161} INFO - Started process (PID=39909) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:25.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:26.215+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:26.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:26.835+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:26.806+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:26.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:27.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 1.947 seconds
[2025-08-15T00:00:37.504+0000] {processor.py:161} INFO - Started process (PID=39919) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:37.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:37.512+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:37.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:37.528+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:37.526+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:37.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:37.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.117 seconds
[2025-08-15T00:00:48.818+0000] {processor.py:161} INFO - Started process (PID=39929) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:48.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:48.838+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:48.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:48.866+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:48.861+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:48.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:48.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.188 seconds
[2025-08-15T00:00:59.302+0000] {processor.py:161} INFO - Started process (PID=39939) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:59.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:00:59.313+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:59.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:59.344+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:00:59.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:00:59.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:00:59.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.134 seconds
[2025-08-15T00:01:09.636+0000] {processor.py:161} INFO - Started process (PID=39949) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:09.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:01:09.643+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:09.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:09.659+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:09.655+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:01:09.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:09.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.069 seconds
[2025-08-15T00:01:19.865+0000] {processor.py:161} INFO - Started process (PID=39959) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:19.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:01:19.872+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:19.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:19.891+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:19.886+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:01:19.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:19.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.077 seconds
[2025-08-15T00:01:30.584+0000] {processor.py:161} INFO - Started process (PID=39969) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:30.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:01:30.590+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:30.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:30.611+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:30.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:01:30.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:30.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.092 seconds
[2025-08-15T00:01:40.829+0000] {processor.py:161} INFO - Started process (PID=39979) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:40.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:01:40.832+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:40.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:40.845+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:40.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:01:40.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:40.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.049 seconds
[2025-08-15T00:01:51.118+0000] {processor.py:161} INFO - Started process (PID=39989) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:51.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:01:51.125+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:51.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:51.148+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:01:51.138+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:01:51.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:01:51.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.094 seconds
[2025-08-15T00:02:01.415+0000] {processor.py:161} INFO - Started process (PID=39999) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:01.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:02:01.419+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:01.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:01.434+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:01.431+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:02:01.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:01.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.071 seconds
[2025-08-15T00:02:11.644+0000] {processor.py:161} INFO - Started process (PID=40009) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:11.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:02:11.648+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:11.647+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:11.663+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:11.656+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:02:11.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:11.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.084 seconds
[2025-08-15T00:02:21.922+0000] {processor.py:161} INFO - Started process (PID=40019) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:21.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:02:21.930+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:21.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:21.953+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:21.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:02:21.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:22.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.101 seconds
[2025-08-15T00:02:33.054+0000] {processor.py:161} INFO - Started process (PID=40029) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:33.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:02:33.063+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:33.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:33.078+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:33.069+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:02:33.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:33.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.080 seconds
[2025-08-15T00:02:43.386+0000] {processor.py:161} INFO - Started process (PID=40039) to work on /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:43.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/check_minio_file.py for tasks to queue
[2025-08-15T00:02:43.392+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:43.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:43.407+0000] {logging_mixin.py:188} INFO - [2025-08-15T00:02:43.399+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/scripts/check_minio_file.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/check_minio_file.py", line 13, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2025-08-15T00:02:43.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/check_minio_file.py
[2025-08-15T00:02:43.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/check_minio_file.py took 0.068 seconds
